<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.

 * SuiteCRM is an extension to SugarCRM Community Edition developed by Salesagility Ltd.
 * Copyright (C) 2011 - 2014 Salesagility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 ********************************************************************************/


// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '6.5.24',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => '',
  'author' => 'David Largo',
  'description' => 'Custom fields and relationship for modules:
Products / Quotes / Accounts / Projets 
Projet: EGO System',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'EGOSystem_custom_modules',
  'published_date' => '2017-01-02 19:58:39',
  'type' => 'module',
  'version' => 1483387124,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'EGOSystem_custom_modules',
  'relationships' => 
  array (
    0 => 
    array (
      'meta_data' => '<basepath>/metadata/project_aos_products_1MetaData.php',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/include/language/en_us.EGOSystem_custom_modules.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/include/language/es_ES.EGOSystem_custom_modules.php',
      'to_module' => 'application',
      'language' => 'es_ES',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/include/language/fr_FR.EGOSystem_custom_modules.php',
      'to_module' => 'application',
      'language' => 'fr_FR',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Quotes/language/en_us.lang.php',
      'to_module' => 'AOS_Quotes',
      'language' => 'en_us',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Project/language/en_us.lang.php',
      'to_module' => 'Project',
      'language' => 'en_us',
    ),
  ),
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Quotes/metadata/editviewdefs.php',
      'to' => 'custom/modules/AOS_Quotes/metadata/editviewdefs.php',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Quotes/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/AOS_Quotes/metadata/editviewdefs.php',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Quotes/metadata/listviewdefs.php',
      'to' => 'custom/modules/AOS_Quotes/metadata/listviewdefs.php',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/detailviewdefs.php',
      'to' => 'custom/modules/Accounts/metadata/detailviewdefs.php',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/detailviewdefs.php',
      'to' => 'custom/working/modules/Accounts/metadata/detailviewdefs.php',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/editviewdefs.php',
      'to' => 'custom/modules/Accounts/metadata/editviewdefs.php',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/Accounts/metadata/editviewdefs.php',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/quickcreatedefs.php',
      'to' => 'custom/modules/Accounts/metadata/quickcreatedefs.php',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/quickcreatedefs.php',
      'to' => 'custom/working/modules/Accounts/metadata/quickcreatedefs.php',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/searchdefs.php',
      'to' => 'custom/modules/Accounts/metadata/searchdefs.php',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/searchdefs.php',
      'to' => 'custom/working/modules/Accounts/metadata/searchdefs.php',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Project/metadata/SearchFields.php',
      'to' => 'custom/modules/Project/metadata/SearchFields.php',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Project/metadata/SearchFields.php',
      'to' => 'custom/working/modules/Project/metadata/SearchFields.php',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Project/metadata/detailviewdefs.php',
      'to' => 'custom/modules/Project/metadata/detailviewdefs.php',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Project/metadata/detailviewdefs.php',
      'to' => 'custom/working/modules/Project/metadata/detailviewdefs.php',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Project/metadata/editviewdefs.php',
      'to' => 'custom/modules/Project/metadata/editviewdefs.php',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Project/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/Project/metadata/editviewdefs.php',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Project/metadata/quickcreatedefs.php',
      'to' => 'custom/modules/Project/metadata/quickcreatedefs.php',
    ),
    18 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Project/metadata/quickcreatedefs.php',
      'to' => 'custom/working/modules/Project/metadata/quickcreatedefs.php',
    ),
    19 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Project/metadata/searchdefs.php',
      'to' => 'custom/modules/Project/metadata/searchdefs.php',
    ),
    20 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Project/metadata/searchdefs.php',
      'to' => 'custom/working/modules/Project/metadata/searchdefs.php',
    ),
    21 => 
    array (
      'from' => '<basepath>/Extension/modules/AOS_Products/Ext/Vardefs/project_aos_products_1_AOS_Products.php',
      'to' => 'custom/Extension/modules/AOS_Products/Ext/Vardefs/project_aos_products_1_AOS_Products.php',
    ),
    22 => 
    array (
      'from' => '<basepath>/Extension/modules/AOS_Products/Ext/Layoutdefs/project_aos_products_1_AOS_Products.php',
      'to' => 'custom/Extension/modules/AOS_Products/Ext/Layoutdefs/project_aos_products_1_AOS_Products.php',
    ),
    23 => 
    array (
      'from' => '<basepath>/Extension/modules/AOS_Products/Ext/Language/es_ES.customproject_aos_products_1.php',
      'to' => 'custom/Extension/modules/AOS_Products/Ext/Language/es_ES.customproject_aos_products_1.php',
    ),
    24 => 
    array (
      'from' => '<basepath>/Extension/modules/AOS_Products/Ext/Language/fr_FR.customproject_aos_products_1.php',
      'to' => 'custom/Extension/modules/AOS_Products/Ext/Language/fr_FR.customproject_aos_products_1.php',
    ),
    25 => 
    array (
      'from' => '<basepath>/Extension/modules/AOS_Products/Ext/Language/en_us.customproject_aos_products_1.php',
      'to' => 'custom/Extension/modules/AOS_Products/Ext/Language/en_us.customproject_aos_products_1.php',
    ),
    26 => 
    array (
      'from' => '<basepath>/Extension/modules/AOS_Quotes/Ext/Vardefs/sugarfield_stage.php',
      'to' => 'custom/Extension/modules/AOS_Quotes/Ext/Vardefs/sugarfield_stage.php',
    ),
    27 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/sugarfield_jjwg_maps_lat_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/sugarfield_jjwg_maps_lat_c.php',
    ),
    28 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/sugarfield_jjwg_maps_address_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/sugarfield_jjwg_maps_address_c.php',
    ),
    29 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/sugarfield_jjwg_maps_geocode_status_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/sugarfield_jjwg_maps_geocode_status_c.php',
    ),
    30 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/sugarfield_jjwg_maps_lng_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/sugarfield_jjwg_maps_lng_c.php',
    ),
    31 => 
    array (
      'from' => '<basepath>/Extension/modules/Project/Ext/Vardefs/sugarfield_show_datetime_c.php',
      'to' => 'custom/Extension/modules/Project/Ext/Vardefs/sugarfield_show_datetime_c.php',
    ),
    32 => 
    array (
      'from' => '<basepath>/Extension/modules/Project/Ext/Vardefs/sugarfield_currency_id.php',
      'to' => 'custom/Extension/modules/Project/Ext/Vardefs/sugarfield_currency_id.php',
    ),
    33 => 
    array (
      'from' => '<basepath>/Extension/modules/Project/Ext/Vardefs/sugarfield_event_insurance_c.php',
      'to' => 'custom/Extension/modules/Project/Ext/Vardefs/sugarfield_event_insurance_c.php',
    ),
    34 => 
    array (
      'from' => '<basepath>/Extension/modules/Project/Ext/Vardefs/sugarfield_account_id_c.php',
      'to' => 'custom/Extension/modules/Project/Ext/Vardefs/sugarfield_account_id_c.php',
    ),
    35 => 
    array (
      'from' => '<basepath>/Extension/modules/Project/Ext/Vardefs/sugarfield_music_provider_c.php',
      'to' => 'custom/Extension/modules/Project/Ext/Vardefs/sugarfield_music_provider_c.php',
    ),
    36 => 
    array (
      'from' => '<basepath>/Extension/modules/Project/Ext/Vardefs/sugarfield_work_space_c.php',
      'to' => 'custom/Extension/modules/Project/Ext/Vardefs/sugarfield_work_space_c.php',
    ),
    37 => 
    array (
      'from' => '<basepath>/Extension/modules/Project/Ext/Vardefs/sugarfield_technical_detail_c.php',
      'to' => 'custom/Extension/modules/Project/Ext/Vardefs/sugarfield_technical_detail_c.php',
    ),
    38 => 
    array (
      'from' => '<basepath>/Extension/modules/Project/Ext/Vardefs/sugarfield_defrayed_night_c.php',
      'to' => 'custom/Extension/modules/Project/Ext/Vardefs/sugarfield_defrayed_night_c.php',
    ),
    39 => 
    array (
      'from' => '<basepath>/Extension/modules/Project/Ext/Vardefs/sugarfield_account_id2_c.php',
      'to' => 'custom/Extension/modules/Project/Ext/Vardefs/sugarfield_account_id2_c.php',
    ),
    40 => 
    array (
      'from' => '<basepath>/Extension/modules/Project/Ext/Vardefs/sugarfield_dressing_rom_c.php',
      'to' => 'custom/Extension/modules/Project/Ext/Vardefs/sugarfield_dressing_rom_c.php',
    ),
    41 => 
    array (
      'from' => '<basepath>/Extension/modules/Project/Ext/Vardefs/sugarfield_sound_c.php',
      'to' => 'custom/Extension/modules/Project/Ext/Vardefs/sugarfield_sound_c.php',
    ),
    42 => 
    array (
      'from' => '<basepath>/Extension/modules/Project/Ext/Vardefs/sugarfield_defrayed_drink_c.php',
      'to' => 'custom/Extension/modules/Project/Ext/Vardefs/sugarfield_defrayed_drink_c.php',
    ),
    43 => 
    array (
      'from' => '<basepath>/Extension/modules/Project/Ext/Vardefs/sugarfield_light_provider_c.php',
      'to' => 'custom/Extension/modules/Project/Ext/Vardefs/sugarfield_light_provider_c.php',
    ),
    44 => 
    array (
      'from' => '<basepath>/Extension/modules/Project/Ext/Vardefs/sugarfield_defrayed_food_c.php',
      'to' => 'custom/Extension/modules/Project/Ext/Vardefs/sugarfield_defrayed_food_c.php',
    ),
    45 => 
    array (
      'from' => '<basepath>/Extension/modules/Project/Ext/Vardefs/sugarfield_electricity_c.php',
      'to' => 'custom/Extension/modules/Project/Ext/Vardefs/sugarfield_electricity_c.php',
    ),
    46 => 
    array (
      'from' => '<basepath>/Extension/modules/Project/Ext/Vardefs/project_aos_products_1_Project.php',
      'to' => 'custom/Extension/modules/Project/Ext/Vardefs/project_aos_products_1_Project.php',
    ),
    47 => 
    array (
      'from' => '<basepath>/Extension/modules/Project/Ext/Vardefs/sugarfield_jjwg_maps_address_c.php',
      'to' => 'custom/Extension/modules/Project/Ext/Vardefs/sugarfield_jjwg_maps_address_c.php',
    ),
    48 => 
    array (
      'from' => '<basepath>/Extension/modules/Project/Ext/Vardefs/sugarfield_contact_c.php',
      'to' => 'custom/Extension/modules/Project/Ext/Vardefs/sugarfield_contact_c.php',
    ),
    49 => 
    array (
      'from' => '<basepath>/Extension/modules/Project/Ext/Vardefs/sugarfield_jjwg_maps_lat_c.php',
      'to' => 'custom/Extension/modules/Project/Ext/Vardefs/sugarfield_jjwg_maps_lat_c.php',
    ),
    50 => 
    array (
      'from' => '<basepath>/Extension/modules/Project/Ext/Vardefs/sugarfield_account_id1_c.php',
      'to' => 'custom/Extension/modules/Project/Ext/Vardefs/sugarfield_account_id1_c.php',
    ),
    51 => 
    array (
      'from' => '<basepath>/Extension/modules/Project/Ext/Vardefs/sugarfield_jjwg_maps_geocode_status_c.php',
      'to' => 'custom/Extension/modules/Project/Ext/Vardefs/sugarfield_jjwg_maps_geocode_status_c.php',
    ),
    52 => 
    array (
      'from' => '<basepath>/Extension/modules/Project/Ext/Vardefs/sugarfield_floor_fix_c.php',
      'to' => 'custom/Extension/modules/Project/Ext/Vardefs/sugarfield_floor_fix_c.php',
    ),
    53 => 
    array (
      'from' => '<basepath>/Extension/modules/Project/Ext/Vardefs/sugarfield_type_c.php',
      'to' => 'custom/Extension/modules/Project/Ext/Vardefs/sugarfield_type_c.php',
    ),
    54 => 
    array (
      'from' => '<basepath>/Extension/modules/Project/Ext/Vardefs/sugarfield_defrayed_travel_c.php',
      'to' => 'custom/Extension/modules/Project/Ext/Vardefs/sugarfield_defrayed_travel_c.php',
    ),
    55 => 
    array (
      'from' => '<basepath>/Extension/modules/Project/Ext/Vardefs/sugarfield_event_advertising_c.php',
      'to' => 'custom/Extension/modules/Project/Ext/Vardefs/sugarfield_event_advertising_c.php',
    ),
    56 => 
    array (
      'from' => '<basepath>/Extension/modules/Project/Ext/Vardefs/sugarfield_sky_fix_c.php',
      'to' => 'custom/Extension/modules/Project/Ext/Vardefs/sugarfield_sky_fix_c.php',
    ),
    57 => 
    array (
      'from' => '<basepath>/Extension/modules/Project/Ext/Vardefs/sugarfield_budget_c.php',
      'to' => 'custom/Extension/modules/Project/Ext/Vardefs/sugarfield_budget_c.php',
    ),
    58 => 
    array (
      'from' => '<basepath>/Extension/modules/Project/Ext/Vardefs/sugarfield_jjwg_maps_lng_c.php',
      'to' => 'custom/Extension/modules/Project/Ext/Vardefs/sugarfield_jjwg_maps_lng_c.php',
    ),
    59 => 
    array (
      'from' => '<basepath>/Extension/modules/Project/Ext/Layoutdefs/project_aos_products_1_Project.php',
      'to' => 'custom/Extension/modules/Project/Ext/Layoutdefs/project_aos_products_1_Project.php',
    ),
    60 => 
    array (
      'from' => '<basepath>/Extension/modules/Project/Ext/Language/fr_FR.customproject_aos_products_1.php',
      'to' => 'custom/Extension/modules/Project/Ext/Language/fr_FR.customproject_aos_products_1.php',
    ),
    61 => 
    array (
      'from' => '<basepath>/Extension/modules/Project/Ext/Language/es_ES.customproject_aos_products_1.php',
      'to' => 'custom/Extension/modules/Project/Ext/Language/es_ES.customproject_aos_products_1.php',
    ),
    62 => 
    array (
      'from' => '<basepath>/Extension/modules/Project/Ext/Language/en_us.customproject_aos_products_1.php',
      'to' => 'custom/Extension/modules/Project/Ext/Language/en_us.customproject_aos_products_1.php',
    ),
    63 => 
    array (
      'from' => '<basepath>/Extension/modules/relationships/layoutdefs/project_aos_products_1_AOS_Products.php',
      'to' => 'custom/Extension/modules/relationships/layoutdefs/project_aos_products_1_AOS_Products.php',
    ),
    64 => 
    array (
      'from' => '<basepath>/Extension/modules/relationships/layoutdefs/project_aos_products_1_Project.php',
      'to' => 'custom/Extension/modules/relationships/layoutdefs/project_aos_products_1_Project.php',
    ),
    65 => 
    array (
      'from' => '<basepath>/Extension/modules/relationships/vardefs/project_aos_products_1_AOS_Products.php',
      'to' => 'custom/Extension/modules/relationships/vardefs/project_aos_products_1_AOS_Products.php',
    ),
    66 => 
    array (
      'from' => '<basepath>/Extension/modules/relationships/vardefs/project_aos_products_1_Project.php',
      'to' => 'custom/Extension/modules/relationships/vardefs/project_aos_products_1_Project.php',
    ),
    67 => 
    array (
      'from' => '<basepath>/Extension/modules/relationships/relationships/project_aos_products_1MetaData.php',
      'to' => 'custom/Extension/modules/relationships/relationships/project_aos_products_1MetaData.php',
    ),
  ),
  'custom_fields' => 
  array (
    'Projectaccount_id1_c' => 
    array (
      'id' => 'Projectaccount_id1_c',
      'name' => 'account_id1_c',
      'label' => 'LBL_MUSIC_PROVIDER_ACCOUNT_ID',
      'comments' => '',
      'help' => '',
      'module' => 'Project',
      'type' => 'id',
      'max_size' => '36',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2016-12-14 18:14:32',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Projectaccount_id2_c' => 
    array (
      'id' => 'Projectaccount_id2_c',
      'name' => 'account_id2_c',
      'label' => 'LBL_CONTACT_ACCOUNT_ID',
      'comments' => '',
      'help' => '',
      'module' => 'Project',
      'type' => 'id',
      'max_size' => '36',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2016-12-14 18:30:43',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Projectaccount_id_c' => 
    array (
      'id' => 'Projectaccount_id_c',
      'name' => 'account_id_c',
      'label' => 'LBL_LIGHT_PROVIDER_ACCOUNT_ID',
      'comments' => '',
      'help' => '',
      'module' => 'Project',
      'type' => 'id',
      'max_size' => '36',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2016-12-14 18:13:52',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Projectbudget_c' => 
    array (
      'id' => 'Projectbudget_c',
      'name' => 'budget_c',
      'label' => 'LBL_BUDGET',
      'comments' => '',
      'help' => '',
      'module' => 'Project',
      'type' => 'currency',
      'max_size' => '26',
      'require_option' => '1',
      'default_value' => '',
      'date_modified' => '2016-12-14 18:06:00',
      'deleted' => '0',
      'audited' => '1',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Projectcontact_c' => 
    array (
      'id' => 'Projectcontact_c',
      'name' => 'contact_c',
      'label' => 'LBL_CONTACT',
      'comments' => '',
      'help' => '',
      'module' => 'Project',
      'type' => 'relate',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2016-12-14 18:30:43',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => 'Accounts',
      'ext3' => 'account_id2_c',
      'ext4' => '',
    ),
    'Projectcurrency_id' => 
    array (
      'id' => 'Projectcurrency_id',
      'name' => 'currency_id',
      'label' => 'LBL_CURRENCY',
      'comments' => '',
      'help' => '',
      'module' => 'Project',
      'type' => 'currency_id',
      'max_size' => '36',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2016-12-14 18:06:00',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Projectdefrayed_drink_c' => 
    array (
      'id' => 'Projectdefrayed_drink_c',
      'name' => 'defrayed_drink_c',
      'label' => 'LBL_DEFRAYED_DRINK',
      'comments' => '',
      'help' => '',
      'module' => 'Project',
      'type' => 'bool',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '1',
      'date_modified' => '2016-12-14 18:22:29',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Projectdefrayed_food_c' => 
    array (
      'id' => 'Projectdefrayed_food_c',
      'name' => 'defrayed_food_c',
      'label' => 'LBL_DEFRAYED_FOOD',
      'comments' => '',
      'help' => '',
      'module' => 'Project',
      'type' => 'bool',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '1',
      'date_modified' => '2016-12-14 18:22:11',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Projectdefrayed_night_c' => 
    array (
      'id' => 'Projectdefrayed_night_c',
      'name' => 'defrayed_night_c',
      'label' => 'LBL_DEFRAYED_NIGHT',
      'comments' => '',
      'help' => '',
      'module' => 'Project',
      'type' => 'bool',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '0',
      'date_modified' => '2016-12-14 18:18:53',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Projectdefrayed_travel_c' => 
    array (
      'id' => 'Projectdefrayed_travel_c',
      'name' => 'defrayed_travel_c',
      'label' => 'LBL_DEFRAYED_TRAVEL',
      'comments' => '',
      'help' => '',
      'module' => 'Project',
      'type' => 'bool',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '0',
      'date_modified' => '2016-12-14 18:22:49',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Projectdressing_rom_c' => 
    array (
      'id' => 'Projectdressing_rom_c',
      'name' => 'dressing_rom_c',
      'label' => 'LBL_DRESSING_ROM',
      'comments' => '',
      'help' => '',
      'module' => 'Project',
      'type' => 'bool',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '1',
      'date_modified' => '2016-12-14 18:29:53',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Projectelectricity_c' => 
    array (
      'id' => 'Projectelectricity_c',
      'name' => 'electricity_c',
      'label' => 'LBL_ELECTRICITY',
      'comments' => '',
      'help' => '',
      'module' => 'Project',
      'type' => 'bool',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '1',
      'date_modified' => '2016-12-14 18:10:44',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Projectevent_advertising_c' => 
    array (
      'id' => 'Projectevent_advertising_c',
      'name' => 'event_advertising_c',
      'label' => 'LBL_EVENT_ADVERTISING',
      'comments' => '',
      'help' => '',
      'module' => 'Project',
      'type' => 'bool',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '1',
      'date_modified' => '2016-12-14 18:24:39',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Projectevent_insurance_c' => 
    array (
      'id' => 'Projectevent_insurance_c',
      'name' => 'event_insurance_c',
      'label' => 'LBL_EVENT_INSURANCE',
      'comments' => '',
      'help' => '',
      'module' => 'Project',
      'type' => 'bool',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '1',
      'date_modified' => '2016-12-14 18:24:07',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Projectfloor_fix_c' => 
    array (
      'id' => 'Projectfloor_fix_c',
      'name' => 'floor_fix_c',
      'label' => 'LBL_FLOOR_FIX',
      'comments' => '',
      'help' => '',
      'module' => 'Project',
      'type' => 'bool',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '0',
      'date_modified' => '2016-12-14 18:09:46',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Projectjjwg_maps_address_c' => 
    array (
      'id' => 'Projectjjwg_maps_address_c',
      'name' => 'jjwg_maps_address_c',
      'label' => 'LBL_JJWG_MAPS_ADDRESS',
      'comments' => 'Address',
      'help' => 'Address',
      'module' => 'Project',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2016-12-10 17:25:35',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Projectjjwg_maps_geocode_status_c' => 
    array (
      'id' => 'Projectjjwg_maps_geocode_status_c',
      'name' => 'jjwg_maps_geocode_status_c',
      'label' => 'LBL_JJWG_MAPS_GEOCODE_STATUS',
      'comments' => 'Geocode Status',
      'help' => 'Geocode Status',
      'module' => 'Project',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2016-12-10 17:25:35',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Projectjjwg_maps_lat_c' => 
    array (
      'id' => 'Projectjjwg_maps_lat_c',
      'name' => 'jjwg_maps_lat_c',
      'label' => 'LBL_JJWG_MAPS_LAT',
      'comments' => NULL,
      'help' => 'Latitude',
      'module' => 'Project',
      'type' => 'float',
      'max_size' => '10',
      'require_option' => '0',
      'default_value' => '0.00000000',
      'date_modified' => '2016-12-10 17:25:35',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '8',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Projectjjwg_maps_lng_c' => 
    array (
      'id' => 'Projectjjwg_maps_lng_c',
      'name' => 'jjwg_maps_lng_c',
      'label' => 'LBL_JJWG_MAPS_LNG',
      'comments' => NULL,
      'help' => 'Longitude',
      'module' => 'Project',
      'type' => 'float',
      'max_size' => '11',
      'require_option' => '0',
      'default_value' => '0.00000000',
      'date_modified' => '2016-12-10 17:25:35',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '8',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Projectlight_provider_c' => 
    array (
      'id' => 'Projectlight_provider_c',
      'name' => 'light_provider_c',
      'label' => 'LBL_LIGHT_PROVIDER',
      'comments' => '',
      'help' => '',
      'module' => 'Project',
      'type' => 'relate',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2016-12-14 18:13:52',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => 'Accounts',
      'ext3' => 'account_id_c',
      'ext4' => '',
    ),
    'Projectmusic_provider_c' => 
    array (
      'id' => 'Projectmusic_provider_c',
      'name' => 'music_provider_c',
      'label' => 'LBL_MUSIC_PROVIDER',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'Project',
      'type' => 'relate',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2016-12-14 18:15:02',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => 'Accounts',
      'ext3' => 'account_id1_c',
      'ext4' => NULL,
    ),
    'Projectshow_datetime_c' => 
    array (
      'id' => 'Projectshow_datetime_c',
      'name' => 'show_datetime_c',
      'label' => 'LBL_SHOW_DATETIME',
      'comments' => '',
      'help' => '',
      'module' => 'Project',
      'type' => 'datetimecombo',
      'max_size' => NULL,
      'require_option' => '1',
      'default_value' => '',
      'date_modified' => '2016-12-14 18:04:50',
      'deleted' => '0',
      'audited' => '1',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Projectsky_fix_c' => 
    array (
      'id' => 'Projectsky_fix_c',
      'name' => 'sky_fix_c',
      'label' => 'LBL_SKY_FIX',
      'comments' => '',
      'help' => '',
      'module' => 'Project',
      'type' => 'bool',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '0',
      'date_modified' => '2016-12-14 18:10:08',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Projectsound_c' => 
    array (
      'id' => 'Projectsound_c',
      'name' => 'sound_c',
      'label' => 'LBL_SOUND',
      'comments' => '',
      'help' => '',
      'module' => 'Project',
      'type' => 'bool',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '1',
      'date_modified' => '2016-12-14 18:11:22',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Projecttechnical_detail_c' => 
    array (
      'id' => 'Projecttechnical_detail_c',
      'name' => 'technical_detail_c',
      'label' => 'LBL_TECHNICAL_DETAIL',
      'comments' => '',
      'help' => '',
      'module' => 'Project',
      'type' => 'text',
      'max_size' => NULL,
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2016-12-14 18:16:26',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '4',
      'ext3' => '80',
      'ext4' => '',
    ),
    'Projecttype_c' => 
    array (
      'id' => 'Projecttype_c',
      'name' => 'type_c',
      'label' => 'LBL_TYPE',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'Project',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '1',
      'default_value' => '1',
      'date_modified' => '2016-12-14 18:02:01',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'projet_type_list',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Projectwork_space_c' => 
    array (
      'id' => 'Projectwork_space_c',
      'name' => 'work_space_c',
      'label' => 'LBL_WORK_SPACE',
      'comments' => '',
      'help' => '',
      'module' => 'Project',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '8mx8m',
      'date_modified' => '2016-12-14 18:08:15',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
  ),
);