<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.

 * SuiteCRM is an extension to SugarCRM Community Edition developed by Salesagility Ltd.
 * Copyright (C) 2011 - 2014 Salesagility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 ********************************************************************************/


// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'EGO',
  'author' => 'David Largo',
  'description' => 'École . Gestion et Organisation pour l&#039;école de cirque',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'EGOCirque',
  'published_date' => '2017-01-03 10:04:34',
  'type' => 'module',
  'version' => 1483437874,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'EGOCirque',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'EGO_Themes',
      'class' => 'EGO_Themes',
      'path' => 'modules/EGO_Themes/EGO_Themes.php',
      'tab' => true,
    ),
    1 => 
    array (
      'module' => 'EGO_Coursesprice',
      'class' => 'EGO_Coursesprice',
      'path' => 'modules/EGO_Coursesprice/EGO_Coursesprice.php',
      'tab' => true,
    ),
    2 => 
    array (
      'module' => 'EGO_Coursesrate',
      'class' => 'EGO_Coursesrate',
      'path' => 'modules/EGO_Coursesrate/EGO_Coursesrate.php',
      'tab' => true,
    ),
    3 => 
    array (
      'module' => 'EGO_Courses',
      'class' => 'EGO_Courses',
      'path' => 'modules/EGO_Courses/EGO_Courses.php',
      'tab' => true,
    ),
    4 => 
    array (
      'module' => 'EGO_Holidays',
      'class' => 'EGO_Holidays',
      'path' => 'modules/EGO_Holidays/EGO_Holidays.php',
      'tab' => true,
    ),
    5 => 
    array (
      'module' => 'EGO_Academicyear',
      'class' => 'EGO_Academicyear',
      'path' => 'modules/EGO_Academicyear/EGO_Academicyear.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/ego_coursesprice_contacts_Contacts.php',
      'to_module' => 'Contacts',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/ego_coursesprice_contacts_EGO_Coursesprice.php',
      'to_module' => 'EGO_Coursesprice',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/ego_courses_contacts_Contacts.php',
      'to_module' => 'Contacts',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/ego_courses_contacts_EGO_Courses.php',
      'to_module' => 'EGO_Courses',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/ego_courses_leads_Leads.php',
      'to_module' => 'Leads',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/ego_courses_leads_EGO_Courses.php',
      'to_module' => 'EGO_Courses',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/ego_academicyear_ego_courses_EGO_Academicyear.php',
      'to_module' => 'EGO_Academicyear',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/ego_academicyear_ego_coursesrate_EGO_Academicyear.php',
      'to_module' => 'EGO_Academicyear',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/ego_academicyear_ego_coursesprice_EGO_Academicyear.php',
      'to_module' => 'EGO_Academicyear',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/ego_academicyear_ego_holidays_EGO_Academicyear.php',
      'to_module' => 'EGO_Academicyear',
    ),
  ),
  'relationships' => 
  array (
    0 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/ego_coursesprice_contactsMetaData.php',
    ),
    1 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/ego_courses_contactsMetaData.php',
    ),
    2 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/ego_courses_leadsMetaData.php',
    ),
    3 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/ego_academicyear_ego_coursesMetaData.php',
    ),
    4 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/ego_academicyear_ego_coursesrateMetaData.php',
    ),
    5 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/ego_academicyear_ego_coursespriceMetaData.php',
    ),
    6 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/ego_academicyear_ego_holidaysMetaData.php',
    ),
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/EGO_Themes',
      'to' => 'modules/EGO_Themes',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/EGO_Coursesprice',
      'to' => 'modules/EGO_Coursesprice',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/EGO_Coursesrate',
      'to' => 'modules/EGO_Coursesrate',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/EGO_Courses',
      'to' => 'modules/EGO_Courses',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/EGO_Holidays',
      'to' => 'modules/EGO_Holidays',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/modules/EGO_Academicyear',
      'to' => 'modules/EGO_Academicyear',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'fr_FR',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'es_ES',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/EGO_Coursesprice.php',
      'to_module' => 'EGO_Coursesprice',
      'language' => 'en_us',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/EGO_Coursesprice.php',
      'to_module' => 'EGO_Coursesprice',
      'language' => 'fr_FR',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/EGO_Coursesprice.php',
      'to_module' => 'EGO_Coursesprice',
      'language' => 'es_ES',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'en_us',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'fr_FR',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'es_ES',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/EGO_Courses.php',
      'to_module' => 'EGO_Courses',
      'language' => 'en_us',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/EGO_Courses.php',
      'to_module' => 'EGO_Courses',
      'language' => 'fr_FR',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/EGO_Courses.php',
      'to_module' => 'EGO_Courses',
      'language' => 'es_ES',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Leads.php',
      'to_module' => 'Leads',
      'language' => 'en_us',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Leads.php',
      'to_module' => 'Leads',
      'language' => 'fr_FR',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Leads.php',
      'to_module' => 'Leads',
      'language' => 'es_ES',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/EGO_Courses.php',
      'to_module' => 'EGO_Courses',
      'language' => 'en_us',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/EGO_Courses.php',
      'to_module' => 'EGO_Courses',
      'language' => 'fr_FR',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/EGO_Courses.php',
      'to_module' => 'EGO_Courses',
      'language' => 'es_ES',
    ),
    18 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/EGO_Courses.php',
      'to_module' => 'EGO_Courses',
      'language' => 'en_us',
    ),
    19 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/EGO_Courses.php',
      'to_module' => 'EGO_Courses',
      'language' => 'fr_FR',
    ),
    20 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/EGO_Courses.php',
      'to_module' => 'EGO_Courses',
      'language' => 'es_ES',
    ),
    21 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/EGO_Academicyear.php',
      'to_module' => 'EGO_Academicyear',
      'language' => 'en_us',
    ),
    22 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/EGO_Academicyear.php',
      'to_module' => 'EGO_Academicyear',
      'language' => 'fr_FR',
    ),
    23 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/EGO_Academicyear.php',
      'to_module' => 'EGO_Academicyear',
      'language' => 'es_ES',
    ),
    24 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/EGO_Coursesrate.php',
      'to_module' => 'EGO_Coursesrate',
      'language' => 'en_us',
    ),
    25 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/EGO_Coursesrate.php',
      'to_module' => 'EGO_Coursesrate',
      'language' => 'fr_FR',
    ),
    26 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/EGO_Coursesrate.php',
      'to_module' => 'EGO_Coursesrate',
      'language' => 'es_ES',
    ),
    27 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/EGO_Academicyear.php',
      'to_module' => 'EGO_Academicyear',
      'language' => 'en_us',
    ),
    28 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/EGO_Academicyear.php',
      'to_module' => 'EGO_Academicyear',
      'language' => 'fr_FR',
    ),
    29 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/EGO_Academicyear.php',
      'to_module' => 'EGO_Academicyear',
      'language' => 'es_ES',
    ),
    30 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/EGO_Coursesprice.php',
      'to_module' => 'EGO_Coursesprice',
      'language' => 'en_us',
    ),
    31 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/EGO_Coursesprice.php',
      'to_module' => 'EGO_Coursesprice',
      'language' => 'fr_FR',
    ),
    32 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/EGO_Coursesprice.php',
      'to_module' => 'EGO_Coursesprice',
      'language' => 'es_ES',
    ),
    33 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/EGO_Academicyear.php',
      'to_module' => 'EGO_Academicyear',
      'language' => 'en_us',
    ),
    34 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/EGO_Academicyear.php',
      'to_module' => 'EGO_Academicyear',
      'language' => 'fr_FR',
    ),
    35 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/EGO_Academicyear.php',
      'to_module' => 'EGO_Academicyear',
      'language' => 'es_ES',
    ),
    36 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/EGO_Holidays.php',
      'to_module' => 'EGO_Holidays',
      'language' => 'en_us',
    ),
    37 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/EGO_Holidays.php',
      'to_module' => 'EGO_Holidays',
      'language' => 'fr_FR',
    ),
    38 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/EGO_Holidays.php',
      'to_module' => 'EGO_Holidays',
      'language' => 'es_ES',
    ),
    39 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/EGO_Academicyear.php',
      'to_module' => 'EGO_Academicyear',
      'language' => 'en_us',
    ),
    40 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/EGO_Academicyear.php',
      'to_module' => 'EGO_Academicyear',
      'language' => 'fr_FR',
    ),
    41 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/EGO_Academicyear.php',
      'to_module' => 'EGO_Academicyear',
      'language' => 'es_ES',
    ),
    42 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
  ),
  'vardefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/ego_coursesprice_contacts_Contacts.php',
      'to_module' => 'Contacts',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/ego_coursesprice_contacts_EGO_Coursesprice.php',
      'to_module' => 'EGO_Coursesprice',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/ego_courses_contacts_Contacts.php',
      'to_module' => 'Contacts',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/ego_courses_contacts_EGO_Courses.php',
      'to_module' => 'EGO_Courses',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/ego_courses_leads_Leads.php',
      'to_module' => 'Leads',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/ego_courses_leads_EGO_Courses.php',
      'to_module' => 'EGO_Courses',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/ego_academicyear_ego_courses_EGO_Courses.php',
      'to_module' => 'EGO_Courses',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/ego_academicyear_ego_courses_EGO_Academicyear.php',
      'to_module' => 'EGO_Academicyear',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/ego_academicyear_ego_coursesrate_EGO_Coursesrate.php',
      'to_module' => 'EGO_Coursesrate',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/ego_academicyear_ego_coursesrate_EGO_Academicyear.php',
      'to_module' => 'EGO_Academicyear',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/ego_academicyear_ego_coursesprice_EGO_Coursesprice.php',
      'to_module' => 'EGO_Coursesprice',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/ego_academicyear_ego_coursesprice_EGO_Academicyear.php',
      'to_module' => 'EGO_Academicyear',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/ego_academicyear_ego_holidays_EGO_Holidays.php',
      'to_module' => 'EGO_Holidays',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/ego_academicyear_ego_holidays_EGO_Academicyear.php',
      'to_module' => 'EGO_Academicyear',
    ),
  ),
  'layoutfields' => 
  array (
    0 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    1 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    2 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    3 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
  ),
);